#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v10
# autospec commit: 5905be9
#
Name     : rust-bindgen
Version  : 0.69.4
Release  : 1
URL      : https://github.com/rust-lang/rust-bindgen/archive/refs/tags/v0.69.4.tar.gz
Source0  : https://github.com/rust-lang/rust-bindgen/archive/refs/tags/v0.69.4.tar.gz
Source1  : http://localhost/cgit/vendor/rust-bindgen/snapshot/rust-bindgen-2024-04-24-19-19-35.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause HPND ICU MIT Unicode-DFS-2016 Unlicense
Requires: rust-bindgen-bin = %{version}-%{release}
Requires: rust-bindgen-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![crates.io](https://img.shields.io/crates/v/bindgen.svg)](https://crates.io/crates/bindgen)
[![docs.rs](https://docs.rs/bindgen/badge.svg)](https://docs.rs/bindgen/)

%package bin
Summary: bin components for the rust-bindgen package.
Group: Binaries
Requires: rust-bindgen-license = %{version}-%{release}

%description bin
bin components for the rust-bindgen package.


%package license
Summary: license components for the rust-bindgen package.
Group: Default

%description license
license components for the rust-bindgen package.


%prep
%setup -q -n rust-bindgen-0.69.4
cd %{_builddir}
tar xf %{_sourcedir}/rust-bindgen-2024-04-24-19-19-35.tar.xz
cd %{_builddir}/rust-bindgen-0.69.4
mkdir -p ./vendor
cp -r %{_builddir}/rust-bindgen-2024-04-24-19-19-35/* %{_builddir}/rust-bindgen-0.69.4/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
mkdir -p %{buildroot}/usr/share/package-licenses/rust-bindgen
cp %{_builddir}/rust-bindgen-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/8690c5c1d27c8829def121744e5bcd86f48788ef || :
cp %{_builddir}/rust-bindgen-%{version}/bindgen-cli/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/8690c5c1d27c8829def121744e5bcd86f48788ef || :
cp %{_builddir}/rust-bindgen-%{version}/bindgen/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/8690c5c1d27c8829def121744e5bcd86f48788ef || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/annotate-snippets/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/annotate-snippets/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/fdfbda78ad0b863317a64dddfe6491935fc18ffc || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cexpr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cexpr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/cd821ffa80099abbc31c22fe770022f3349e0918 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clang-sys/LICENSE.txt %{buildroot}/usr/share/package-licenses/rust-bindgen/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_complete/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_complete/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/env_logger-0.8.4/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/env_logger-0.8.4/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/env_logger/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/env_logger/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/errno-dragonfly/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/73724f22eb580e208c5af2e3d089be349209e847 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/glob/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/glob/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/humantime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/humantime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ff432d95fdfee3587e45abd61685c2209d245901 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/instant/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/037192733999bccd7ed8d75123b7ec09feb4a12d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/io-lifetimes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/io-lifetimes/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/io-lifetimes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/is-terminal/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/is-terminal/LICENSE-MIT-atty %{buildroot}/usr/share/package-licenses/rust-bindgen/ffe3aa1f76c00b737c79c3a17b9e30163a936bc0 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/lazycell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/lazycell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/bce2ed71de8bb33db2d29a5fcadd7407824e9248 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/libloading/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/4ad37fc99fecc5cda018043361f5b12e350e4052 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys-0.1.4/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys-0.1.4/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys-0.1.4/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/f9cc84dfc567fdc0979fddc3e6257191d8ebc9d8 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/memchr/COPYING %{buildroot}/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/rust-bindgen/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/nom/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/objc/LICENSE.txt %{buildroot}/usr/share/package-licenses/rust-bindgen/b6701831988d077f53d90abce09a2887fc7b5ea9 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/os_str_bytes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/os_str_bytes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/dace34da2cc966a228ddef52cbc28943931af544 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/owo-colors/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/d678d723983cdba8c0182749676fe0ac87e74173 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/prettyplease/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/prettyplease/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro-error-attr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/a88eaffea57a51eedb5291e0d55a959df7659458 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro-error-attr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro-error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/197cb40dc96ded1e036d13ef67fdc7a758ca1388 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro-error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/quickcheck/COPYING %{buildroot}/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/quickcheck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/quickcheck/UNLICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/rust-bindgen/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/rust-bindgen/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/rust-bindgen/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/regex/src/testdata/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/553e82bef8637312393c95bc62e23e8f81fd9e47 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustc-hash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustc-hash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix-0.36.16/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix-0.36.16/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix-0.36.16/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/shlex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/a97a2888bca904918b3b9ec008fde1d6e9905a6d || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/shlex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/similar/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/strsim/LICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/syn-1.0.107/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/syn-1.0.107/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/termcolor/COPYING %{buildroot}/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/termcolor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/termcolor/UNLICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/rust-bindgen/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/rust-bindgen/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/which/LICENSE.txt %{buildroot}/usr/share/package-licenses/rust-bindgen/a8ced9a6c206a0e47fac6c6d0d0ce839e85b2eb7 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/rust-bindgen/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/rust-bindgen/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys-0.42.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys-0.42.0/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys-0.45.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys-0.45.0/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-targets-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-targets-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_gnullvm-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_gnullvm-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_gnu-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_gnu-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnu-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnu-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnullvm-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnullvm-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_msvc-0.42.2/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_msvc-0.42.2/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/rust-bindgen-2024-04-24-19-19-35/yansi-term/LICENCE %{buildroot}/usr/share/package-licenses/rust-bindgen/7293920aac55f4d275cef83ba10d706585622a53 || :
install -D -p -m 0755 target/release/bindgen %{buildroot}/usr/bin/bindgen

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bindgen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rust-bindgen/037192733999bccd7ed8d75123b7ec09feb4a12d
/usr/share/package-licenses/rust-bindgen/197cb40dc96ded1e036d13ef67fdc7a758ca1388
/usr/share/package-licenses/rust-bindgen/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/rust-bindgen/27ea6989d4f34b7b944eb884410a31ae20d11686
/usr/share/package-licenses/rust-bindgen/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/rust-bindgen/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/rust-bindgen/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/rust-bindgen/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/rust-bindgen/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/rust-bindgen/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/rust-bindgen/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/rust-bindgen/4ad37fc99fecc5cda018043361f5b12e350e4052
/usr/share/package-licenses/rust-bindgen/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/rust-bindgen/553e82bef8637312393c95bc62e23e8f81fd9e47
/usr/share/package-licenses/rust-bindgen/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/rust-bindgen/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/rust-bindgen/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/rust-bindgen/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/rust-bindgen/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/rust-bindgen/64e8197cb5ae680fcf996cc0ac8760e9f1e2e3a6
/usr/share/package-licenses/rust-bindgen/655a437377cc2780990746fe2492fa16764df083
/usr/share/package-licenses/rust-bindgen/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/rust-bindgen/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/rust-bindgen/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/rust-bindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/rust-bindgen/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/rust-bindgen/7293920aac55f4d275cef83ba10d706585622a53
/usr/share/package-licenses/rust-bindgen/73724f22eb580e208c5af2e3d089be349209e847
/usr/share/package-licenses/rust-bindgen/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/rust-bindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/rust-bindgen/8690c5c1d27c8829def121744e5bcd86f48788ef
/usr/share/package-licenses/rust-bindgen/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/rust-bindgen/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/rust-bindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/rust-bindgen/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/rust-bindgen/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/rust-bindgen/a88eaffea57a51eedb5291e0d55a959df7659458
/usr/share/package-licenses/rust-bindgen/a8ced9a6c206a0e47fac6c6d0d0ce839e85b2eb7
/usr/share/package-licenses/rust-bindgen/a97a2888bca904918b3b9ec008fde1d6e9905a6d
/usr/share/package-licenses/rust-bindgen/aca374a3362a76702c50bd4e7d590a57f8834fc7
/usr/share/package-licenses/rust-bindgen/b6701831988d077f53d90abce09a2887fc7b5ea9
/usr/share/package-licenses/rust-bindgen/bce2ed71de8bb33db2d29a5fcadd7407824e9248
/usr/share/package-licenses/rust-bindgen/cd3fe820606ed34ac2591caf068c7cabd3ab3509
/usr/share/package-licenses/rust-bindgen/cd821ffa80099abbc31c22fe770022f3349e0918
/usr/share/package-licenses/rust-bindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/rust-bindgen/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/rust-bindgen/d678d723983cdba8c0182749676fe0ac87e74173
/usr/share/package-licenses/rust-bindgen/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/rust-bindgen/dace34da2cc966a228ddef52cbc28943931af544
/usr/share/package-licenses/rust-bindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/rust-bindgen/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/rust-bindgen/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/rust-bindgen/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/rust-bindgen/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/rust-bindgen/f9cc84dfc567fdc0979fddc3e6257191d8ebc9d8
/usr/share/package-licenses/rust-bindgen/fdfbda78ad0b863317a64dddfe6491935fc18ffc
/usr/share/package-licenses/rust-bindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/rust-bindgen/ff432d95fdfee3587e45abd61685c2209d245901
/usr/share/package-licenses/rust-bindgen/ffe3aa1f76c00b737c79c3a17b9e30163a936bc0
